# Generated by Django 4.0.2 on 2022-02-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsongs',
            name='artist_image',
            field=models.CharField(max_length=5500, verbose_name='artist_image'),
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='track_artists',
            field=models.CharField(max_length=2500, verbose_name='track_artists'),
        ),
    ]
