# Generated by Django 4.0.2 on 2022-02-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyFeedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='week_added',
        ),
    ]
