# Generated by Django 4.0.2 on 2022-02-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyFeedback', '0002_remove_playlistsong_week_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='namesample',
            name='slider_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='slider value'),
        ),
    ]
