# Generated by Django 4.0.2 on 2022-02-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyFeedback', '0002_alter_playlistsongs_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsongs',
            name='artist_genres',
            field=models.CharField(max_length=2000, verbose_name='artist_genres'),
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='track_album',
            field=models.CharField(max_length=1000, verbose_name='track_album'),
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='track_name',
            field=models.CharField(max_length=1000, verbose_name='track_name'),
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='track_spotify_address',
            field=models.CharField(max_length=1000, verbose_name='track_spotify_id'),
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='track_src',
            field=models.CharField(max_length=1000, verbose_name='track_src'),
        ),
    ]
