# Generated by Django 4.0.2 on 2022-02-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyFeedback', '0003_namesample_slider_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(max_length=200, verbose_name='option_1')),
                ('option_2', models.CharField(max_length=200, verbose_name='option_2')),
                ('added_on', models.CharField(max_length=200, verbose_name='date_added')),
            ],
            options={
                'verbose_name': 'Slider Question',
                'verbose_name_plural': 'Slider Questions',
            },
        ),
        migrations.CreateModel(
            name='WeeklySlidersSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(max_length=200, verbose_name='option_1')),
                ('option_2', models.CharField(max_length=200, verbose_name='option_2')),
                ('added_on', models.CharField(max_length=200, verbose_name='date_added')),
            ],
            options={
                'verbose_name': 'Suggested Slider Question',
                'verbose_name_plural': 'Suggested Slider Questions',
            },
        ),
    ]
