# Generated by Django 4.0.2 on 2022-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyFeedback', '0006_remove_weeklysliderssuggestion_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklysliders',
            name='question_id',
        ),
        migrations.AddField(
            model_name='weeklysliders',
            name='form_field',
            field=models.CharField(default=float("nan"), max_length=200, verbose_name='algins this to a form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklysliders',
            name='week_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='week_question'),
        ),
    ]
