# Generated by Django 4.0.2 on 2022-02-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyFeedback', '0009_remove_namesample_slider_value_namesample_q1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songreview',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='songreview',
            name='review_response',
        ),
        migrations.AddField(
            model_name='songreview',
            name='q1',
            field=models.IntegerField(blank=True, null=True, verbose_name='slider value'),
        ),
        migrations.AddField(
            model_name='songreview',
            name='q2',
            field=models.IntegerField(blank=True, null=True, verbose_name='slider value'),
        ),
        migrations.AddField(
            model_name='songreview',
            name='q3',
            field=models.IntegerField(blank=True, null=True, verbose_name='slider value'),
        ),
        migrations.AddField(
            model_name='songreview',
            name='username',
            field=models.CharField(default=float("nan"), max_length=200, verbose_name='username_of_who_added'),
            preserve_default=False,
        ),
    ]
